import { PUZZLE_GOAL, isPuzzleGoal, puzzleMoves, puzzleKey } from "../search-eight-puzzle/game-core.js?v=2026081902";
const $=selector=>document.querySelector(selector);
export const PLAY_START=Object.freeze([1,5,2,8,0,3,4,7,6]);
let state=[...PLAY_START],moves=0,recommended=null;
const minimum=8;
const el={board:$("#play-board"),goal:$("#goal-board"),count:$("#move-count"),feedback:$("#feedback"),play:$("#play-area"),results:$("#results"),message:$("#result-message"),reset:$("#reset-game"),restart:$("#restart"),hint:$("#hint"),projector:$("#projector-toggle")};
function describe(board){return [board.slice(0,3),board.slice(3,6),board.slice(6,9)].map(row=>row.map(n=>n||"빈칸").join(" ")).join(", ");}
function adjacent(a,b){return Math.abs(Math.floor(a/3)-Math.floor(b/3))+Math.abs(a%3-b%3)===1;}
function shortestPath(start){const startKey=puzzleKey(start),goalKey=puzzleKey(PUZZLE_GOAL),parents=new Map(),states=new Map([[startKey,start]]),seen=new Set([startKey]),queue=[start];for(let head=0;head<queue.length;head+=1){const current=queue[head],from=puzzleKey(current);if(from===goalKey)break;for(const move of puzzleMoves(current)){const key=puzzleKey(move.state);if(seen.has(key))continue;seen.add(key);parents.set(key,from);states.set(key,move.state);queue.push(move.state);}}if(!seen.has(goalKey))return[];const path=[];let key=goalKey;while(key!==startKey){path.unshift(states.get(key));key=parents.get(key);}return path;}
function renderBoard(container,board,interactive=false){container.innerHTML="";container.setAttribute("aria-label",describe(board));const blank=board.indexOf(0);board.forEach((number,index)=>{if(!number){const gap=document.createElement("span");gap.className="tile blank";gap.setAttribute("aria-hidden","true");container.append(gap);return;}const tile=document.createElement(interactive?"button":"span");tile.className=`tile${interactive&&adjacent(index,blank)?" movable":""}${interactive&&number===recommended?" recommended":""}`;tile.textContent=number;if(interactive){tile.type="button";tile.dataset.index=index;tile.disabled=!adjacent(index,blank);tile.setAttribute("aria-label",`${number}번 타일 움직이기`);}container.append(tile);});}
function render(){renderBoard(el.board,state,true);el.count.textContent=`${moves}회`;}
function reset(){state=[...PLAY_START];moves=0;recommended=null;el.feedback.textContent="빈칸 옆의 숫자를 선택하세요.";el.results.hidden=true;el.play.hidden=false;render();}
el.board.addEventListener("click",event=>{const button=event.target.closest("button[data-index]");if(!button)return;const index=Number(button.dataset.index),blank=state.indexOf(0);recommended=null;[state[index],state[blank]]=[state[blank],state[index]];moves+=1;render();if(isPuzzleGoal(state)){el.play.hidden=true;el.results.hidden=false;el.message.textContent=moves===minimum?`가장 적은 ${minimum}번의 이동으로 완성했습니다.`:`${moves}번 만에 완성했습니다. 가장 짧은 방법은 ${minimum}번입니다.`;el.results.querySelector("h2").focus();document.dispatchEvent(new CustomEvent("eight-puzzle:play-complete"));}else el.feedback.textContent=`${moves}번째 이동 완료. 다음 숫자를 선택하세요.`;});
el.hint.addEventListener("click",()=>{const next=shortestPath(state)[0];if(!next)return;recommended=next[state.indexOf(0)];render();el.feedback.textContent=`${recommended}번 타일을 움직이면 목표에 한 걸음 가까워집니다.`;});
el.reset.addEventListener("click",reset);el.restart.addEventListener("click",reset);
renderBoard(el.goal,PUZZLE_GOAL);render();
